''' This module just stores lists of one category or another '''


#aac-607
valid_suffixes = [
    'AVP.',
    'AVP',
    'ASST.V.P.',
    'ASSISTANT VICE PRESIDENT',
    'ASST. VICE PRESIDENT',
    'CEO',
    'C.E.O.',
    'CHIEF EXECUTIVE OFFICER',
    'CFO',
    'C.F.O.',
    'CHIEF FINANCIAL OFFICER',
    'COO',
    'C.O.O.',
    'CHIEF OPERATING OFFICER',
    'CPA',
    'C.P.A.',
    'CERTIFIED PUBLIC ACCOUNTANT',
    'CLU',
    'C.L.U.',
    'CHARTEREDLIFEUND',
    'CHARTERED LIFE UNDERWRITER',
    'CHARTERED LIFE UND',
    'CHARTERED LIFE UW',
    'CHARTERED LIFE U/W',
    'CPCU',
    'C.P.C.U.',
    'CHARTEREDP/CUND',
    'CHARTERED PROPERTY CASUALTY UNDERWRITER',
    'CHARTERED PROPERTY CASUALTY UW',
    'CHARTERED PROPERTY CASUALTY U/W',
    'CHARTERED P&C UNDERWRITER',
    'CHARTERED P&C UW',
    'CHARTERED P&C U/W',
    'CHARTERED P/C UNDERWRITER',
    'CHARTERED P/C UW',
    'CHARTERED P/C U/W',
    'DDS',
    'D.D.S.',
    'DOCTOR OF DENTAL SURGERY',
    'DOC. OF DENTAL SURGERY',
    'DR. OF DENTAL SURGERY',
    'DELEGATED OFFICER',
    'DIRECTOR OF OPERATIONS',
    'DOCTOR OF OSTEOPATHY',
    'DUTY OFFICER',
    'DEVELOPMENT OFFICER',
    'DIRECTOR OFFICER',
    'DISTRICT OFFICER',
    'DISTRICT OFFICE',
    'DIVISION OFFICER',
    'DOCTOR OF OSTEOPATHIC MEDICINE',
    'DETENTION OFFICER',
    'DESIGNATED OFFICIAL',
    'DISBURSING OFFICER',
    'DISPENSING OPTICIAN',
    'DIRECTORATE OF OPERATIONS (US CIA)',
    'DIVISION OPERATOR',
    'DIVISIONAL OFFICER',
    'DOCTOR OF OTOLARYNGOLOGY',
    'D.O.',
    'D.V.M.',
    'DO',
    'ESQUIRE',
    'ESQ',
    'III.',
    'III',
    'II.',
    'II',
    'IV.',
    'IV',
    'JR.',
    'JR',
    'JUNIOR',
    'MD',
    'M.D.',
    'MGR.',
    'MGR',
    'MANAGER',
    'MOSR',
    'MONSIGNOR',
    'NP',
    'N.P.',
    'NOTARY PUBLIC',
    'PA',
    'P.A.',
    'PC',
    'P.C.',
    'PHD.',
    'PHD',
    'PH.D',
    'DR.',
    'J.D.',
    'PRESIDENT',
    'PRES.',
    'PRES',
    'Q.C.',
    'QC',
    'R.N.',
    'RN',
    'SEAMAN',
    'SMN',
    'SEC.',
    'SEC',
    'SR.',
    'SR',
    'SENIOR',
    'SUPERVISOR',
    'SPV.',
    'SPV',
    'TREASURER',
    'TRS.',
    'TRS',
    'V.',
    'V'
    ]
#/aac-607

occupation_string_to_party_load_code_map_for_pq_province = {
    'PRODUCTION' : '8',
    'MANAGEMENT' : '9',
    'ADMINISTRATIVE SUPPORT' : '9',
    'ADMINISTRATIVE' : '9',
    'PROTECTIVE SERVICE' : '1',
    'FOOD & BEVERAGE' : '5',
    'NURSE' : '17',
    'PROFESSIONAL/TECHNICAL' : '17',
    'HEALTH CARE SPECIALIST' : '17',
    'HOSPITAL TECHNICIAN' : '17',
    'MEDICAL TECHNICIAN' : '17',
    'HEALTH SERVICE' : '17',
    'SURVEYORS' : '3',
    'ARCHITECT' : '3',
    'BIOLOGIST' : '3',
    'DOCTOR' : '17',
    'VETERINARIANS' : '17',
    'SCIENTIST' : '3',
    'URBAN PLANNERS' : '3',
    'AGRONOMIST' : '3',
    'ACTUARY' : '3',
    'ACCOUNTANT' : '3',
    'ENGINEER' : '3',
    'LAWYER, NOTARY' : '3',
    'BELL (ADMIN & OFFICE STAFF)' : '3',
    'NORTHERN (ADMIN & OFFICE STAFF)' : '3',
    'CHARTERED ADMINISTRATION' : '3',
    'INSURANCE BROKER & COMPANY' : '15',
    'MUNICIPALITY EMPLOYEE - ADMINISTRATIVE' : '16',
    'FEDERAL GOVT EMPLOYEE - ADMINISTRATIVE' : '16',
    'GOVERNMENT MANAGEMENT' : '16',
    'EDUCATOR' : '3',
    'UNIVERSITY STAFF' : '9',
    'COLLEGE EMPLOYEE - ADMINISTRATIVE' : '9',
    'HOSPITAL ADMINISTRATIVE STAFF' : '16',
    'UNIVERSITY EMPLOYEE - ADMINISTRATIVE' : '9',
    'FINANCIAL SERVICES SPECIALIST' : '3',
    'FIREFIGHTER' : '16',
    'RETIRED' : '12',
    'MARKETING & SALES' : '4',
    'PERSONAL SERVICE' : '11',
    'BUILDING & GROUND SERVICE' : '11',
    'CONSTRUCTION TRADE' : '2',
    'TRANSPORTATION & MATERIAL MOVING' : '2',
    'MECHANIC, INSTALLER, REPAIRER' : '2',
    'NOT EMPLOYED' : '13',
    'NOT DISCLOSED' : '14',
    'OTHER (PQ ONLY)' : '14'
}

occupation_string_to_party_load_code_map = {
    'NOT DISCLOSED' : '14',
    'NOT EMPLOYED' : '13',
    'RETIRED' : '12',
    'OTHER (PQ ONLY)' : '14',
    'ACCOUNTANT' : '3',
    'ACTUARY' : '3',
    'ARCHITECT' : '3',
    'BIOLOGIST' : '3',
    'DOCTOR' : '3',
    'EDUCATOR' : '18',
    'ENGINEER' : '3',
    'FINANCIAL SERVICES SPECIALIST' : '18',
    'FIREFIGHTER' : '14',
    'GOVERNMENT MANAGEMENT' : '16',
    'LAWYER, NOTARY' : '3',
    'MANAGEMENT' : '9',
    'SCIENTIST' : '3',
    'PROFESSIONAL/TECHNICAL' : '14',
    'BELL (ADMIN & OFFICE STAFF)' : '3',
    'NORTHERN (ADMIN & OFFICE STAFF)' : '3',
    'CHARTERED ADMINISTRATION' : '3',
    'SURVEYORS' : '3',
    'URBAN PLANNERS' : '3',
    'HEALTH CARE SPECIALIST' : '17',
    'HOSPITAL TECHNICIAN' : '17',
    'MEDICAL TECHNICIAN' : '17',
    'NURSE' : '17',
    'INSURANCE BROKER & COMPANY' : '15',
    'UNIVERSITY STAFF' : '18',
    'PROTECTIVE SERVICE' : '1',
    'HEALTH SERVICE' : '11',
    'ADMINISTRATIVE' : '9',
    'AGRONOMIST' : '3',
    'HOSPITAL ADMINISTRATIVE STAFF' : '18',
    'FOOD & BEVERAGE' : '5',
    'PERSONAL SERVICE' : '11',
    'BUILDING & GROUND SERVICE' : '11',
    'MARKETING & SALES' : '4',
    'ADMINISTRATIVE SUPPORT' : '9',
    'MECHANIC, INSTALLER, REPAIRER' : '2',
    'CONSTRUCTION TRADE' : '2',
    'PRODUCTION' : '8',
    'TRANSPORTATION & MATERIAL MOVING' : '2',
    'CANADA POST SUPPORT (PQ ONLY)' : '11',
    'HYDRO QUEBEC SUPPORT (PQ ONLY)' : '11',
    'COLLEGE EMPLOYEE - ADMINISTRATIVE' : '18',
    'MUNICIPALITY EMPLOYEE - ADMINISTRATIVE' : '3',
    'FEDERAL GOVT EMPLOYEE - ADMINISTRATIVE' : '16',
    'UNIVERSITY EMPLOYEE - ADMINISTRATIVE' : '18',
    'VETERINARIANS' : '3'
}


province_code_map = {
    'NN' : 'NU',
    'PQ' : 'QC',
    'AB' : 'AB',
    'AK' : 'AK',
    'AL' : 'AL',
    'AR' : 'AR',
    'AS' : 'AS',
    'AZ' : 'AZ',
    'BC' : 'BC',
    'CA' : 'CA',
    'CO' : 'CO',
    'CT' : 'CT',
    'DC' : 'DC',
    'DE' : 'DE',
    'FL' : 'FL',
    'GA' : 'GA',
    'HI' : 'HI',
    'IA' : 'IA',
    'ID' : 'ID',
    'IL' : 'IL',
    'IN' : 'IN',
    'KS' : 'KS',
    'KY' : 'KY',
    'LA' : 'LA',
    'MA' : 'MA',
    'MB' : 'MB',
    'MD' : 'MD',
    'ME' : 'ME',
    'MI' : 'MI',
    'MN' : 'MN',
    'MO' : 'MO',
    'MS' : 'MS',
    'MT' : 'MT',
    'NB' : 'NB',
    'NC' : 'NC',
    'ND' : 'ND',
    'NE' : 'NE',
    'NL' : 'NL',
    'NH' : 'NH',
    'NJ' : 'NJ',
    'NM' : 'NM',
    'NS' : 'NS',
    'NT' : 'NT',
    'NU' : 'NU',
    'NV' : 'NV',
    'NY' : 'NY',
    'OH' : 'OH',
    'OK' : 'OK',
    'ON' : 'ON',
    'OR' : 'OR',
    'PA' : 'PA',
    'PE' : 'PE',
    'PR' : 'PR',
    'QC' : 'QC',
    'RI' : 'RI',
    'SC' : 'SC',
    'SD' : 'SD',
    'SK' : 'SK',
    'TN' : 'TN',
    'TT' : 'TT',
    'TX' : 'TX',
    'UT' : 'UT',
    'VA' : 'VA',
    'VI' : 'VI',
    'VT' : 'VT',
    'WA' : 'WA',
    'WI' : 'WI',
    'WV' : 'WV',
    'WY' : 'WY',
    'YT' : 'YT'
}

country_code_extract_to_party_load_map = {
    'AB' : 'CA',
    'AK' : 'US',
    'AL' : 'US',
    'AR' : 'US',
    'AS' : 'US',
    'AZ' : 'US',
    'BC' : 'CA',
    'CA' : 'US',
    'CO' : 'US',
    'CT' : 'US',
    'DC' : 'US',
    'DE' : 'US',
    'FL' : 'US',
    'GA' : 'US',
    'HI' : 'US',
    'IA' : 'US',
    'ID' : 'US',
    'IL' : 'US',
    'IN' : 'US',
    'KS' : 'US',
    'KY' : 'US',
    'LA' : 'US',
    'MA' : 'US',
    'MB' : 'CA',
    'MD' : 'US',
    'ME' : 'US',
    'MI' : 'US',
    'MN' : 'US',
    'MO' : 'US',
    'MS' : 'US',
    'MT' : 'US',
    'NB' : 'CA',
    'NC' : 'US',
    'ND' : 'US',
    'NE' : 'US',
    'NL' : 'CA',
    'NH' : 'US',
    'NJ' : 'US',
    'NM' : 'US',
    'NS' : 'CA',
    'NT' : 'CA',
    'NU' : 'CA',
    'NV' : 'US',
    'NY' : 'US',
    'OH' : 'US',
    'OK' : 'US',
    'ON' : 'CA',
    'OR' : 'US',
    'PA' : 'US',
    'PE' : 'CA',
    'PR' : 'US',
    'QC' : 'CA',
    'RI' : 'US',
    'SC' : 'US',
    'SD' : 'US',
    'SK' : 'CA',
    'TN' : 'US',
    'TT' : 'US',
    'TX' : 'US',
    'UT' : 'US',
    'VA' : 'US',
    'VI' : 'US',
    'VT' : 'US',
    'WA' : 'US',
    'WI' : 'US',
    'WV' : 'US',
    'WY' : 'US',
    'YT' : 'CA'
}

organization_name_keywords = [
    'INC',
    'FLOOR',
    ' INC.',
    ' LTD',
    ' LTD.',
    ' LIMITED',
    'CONSTRUCTION',
    'THE TASTE',
    'COMMUNICATION', 
    ' SHOP',
    'DRYWALL',
    'CANADA',
    'COMEDY',
    'CONCRETE',
    'PAVING',
    'PROPERTY',
    'MANAGEMENT',
    'FIRE', 
    'CORPORATION',
    'ELECTRICAL',
    'SUPERSTORE',
    'UNLIMITED',
    'SOLUTIONS',
    'ENTERPRISE',
    'DEVELOPMENT', 
    'TRANSPORTATION',
    'RENOVATIONS',
    'LANDSCAPING',
    'SERVICE',
    'COMPANY',
    'PROOFING',
    'MILLWORKS', 
    ' CABLE',
    ' OPTICAL',
    'CONDOMINIUM',
    'CLEANING',
    'DENTAL',
    'MEDICAL',
    'PROFESSIONAL',
    ' PET', 
    'APARTMENT',
    'FITNESS',
    'PLUMBING',
    'FORMING',
    'VIDEO',
    'CUSTOM',
    'FINISHING',
    ' GAS',
    ' AUTO', 
    ' HOME',
    'ASSOCIATE',
    'TRUST',
    'CONSULTING',
    'CENTRE',
    ' HAIR',
    'BUILDING',
    ' NAIL',
    'RESTAURANT', 
    'GROUP',
    'ENTERPRISES',
    'CONTRACTING',
    'JEWELLERY',
    'CHEMICAL',
    'HOLDINGS',
    'ASSOCIATION', 
    'ANIMAL',
    'UNION',
    'TRUCKING',
    'PAINTING',
    'FOOD',
    'COPTIC',
    'CAPITAL',
    ' SCHOOL',
    ' USA', 
    'CHURCH',
    'EARTHWORKS',
    'SCIENCE',
    'SPORT',
    'STORE',
    'PHARMACY',
    ' HOUSE',
    'SALON',
    'SUSHI', 
    'COUNCIL',
    ' PUB',
    ' ROOFING',
    ' SYSTEM',
    ' HUMAN', 
    # Special / bizarre cases to definitely test for
    '#', 
    'DENTISTRY', 'PLANET', 'SUPER', 'SPEEDY', 
    'SNACK', 'CABLES', 'CABLE', ' OPTICAL', 'ESTHETICS', ' COIN', 'WORKS', 'TATTOO', 'STUDIO', 
    'ADORABLE', 'O/B', 'VARIETY', 'LAUNDROMAT', 'HARDWARE', ' E&O', 'DRILLING', ' HOCKY', 'ONTARIO', 
    'TRAILER', 'FAMILY', 'TECHNOLOG', 'HUMANITY', 'HABITAT', ' FOR', ' CONVENIENCE', ' TOOLS', 
    'PRODUCE', ' BITES', ' SALES', 'CLUB', 'CANADIAN', ' INS', ' CARE ', ' FLYING ', ' INDUSTRI', 
    ' SUPPL', ' ET ', 'SOCIETE', ' CULTURE', 'CHEMINS', ' TRAVAIL', 'S.E.N.C.', ' PROTECTION', 'CLUB', 
    "D'HABITATION", 'COOPÉRATIVE', 'COOPERATIVE', 'CONSERVATOIRE', 'COMMERCE', ' IMMEUBLE', 
    'CONSEIL', 'FILLE', 'RESIDENTIAL', 'MAISON', 'ASSOCIAION', 'CREDIT', 'PROPRIÉTAIRES', ' ENR', 
    ' JARDINS', 'CHEVALIER', 'MARTIAL', 'ENTREPRISE', ' LTEE', 'CAFE', 'LE PAS DE', 'MARCHE', 
    ' BUREAU', 'QUEBEC', 'QUÉBEC', 'MISSIONAIRE', 'MUSÉE', 'NJCC', 'ENR.', ' ARAS', 'MAGASIN', 
    'MASSOTHERAPEUTE', 'METALLIC', 'CHIROPRATIQUE', 'FASRS', 'ENTRETIEN', 'ENVIROVIE', 'AGROCITÉ', 
    'FONDATION', 'CONSULTANT', 'PLEIN AIR', 'SENCRL', 'SIGNATURE', 'PASSE-R-ELLE', 'BIO-NET', 
    'AVOCATES', 'ATELIER', 'QUARTIER', 'LES SCIENTIFINES', 'TEL-AIDE', 'VITRERIE', 'TRANSALMAX', 
    'CHASAM', 'HABITATION', 'GRIFFE', 'LIMITÉE', 'GESTION', 'ALIMENT', 'RENOVATION', ' COOP', 
    'CERCLE DES', 'LES FABULATEURS', 'JANITOR', 'CONTEURS', 'HAMELIN LALANDE SENC', 'SECOND REGARD', 
    ' PLAISIR', 'CLINIQUE', ' MASSE', "L'ACCORDERIE", 'INTERCOM', 'DOMAINE', 'MOBILE', 
    'BOULANGERIE', ' JARDINS', 'RESIDENCE', 'F.A.S.R.S', 'DEMENAGEMENT', 'COIFFURE', 'CO.', 
    # Special / bizarre case to definitely test for
    r'/', 
    'PERFORMANCE',
    'AQUACULTURE',
    'TECHNO',
    '1450 AM',
    'EXCAVATION',
    'THÉRAPEUTE',
    'NOMS ASSURES', 
    'PUBLIC',
    'GOURMET',
    'CAMION',
    'CANADIENNE',
    'SOCIÉTÉ',
    'GROOMING',
    'D.B.A.',
    'FAMILIALE', 
    'NETTOYAGE',
    'IMPRESSION',
    'LAVEUR',
    ' AND ',
    'PERROQUET',
    ' CABANE',
    ' TABLE',
    'CLIMATISATION', 
    ' BAR',
    ' BETON',
    ' OR ',
    'NO.',
    'SCOLAIRE',
    'MEUBLEK',
    'AGROPRODUCTS',
    ' PORTES',
    'PLOMBERIE', 
    'NOVATEL',
    'FORESTIER',
    'MEDIAGRAFIX',
    'INSPECTION',
    'RÉSIDENCE',
    'SAUCISSES',
    ' LTÉE', 
    'GRAPHIQUES',
    ' RADIO',
    'M.S.G.',
    'ESSOUCHEMENT',
    'TUNES',
    'PLAN',
    'SOCIETY',
    'DESIGN', 
    'SHINERS',
    'MUSICAL',
    'MECHANICAL',
    'DIVERS',
    'MOTOR',
    'GALLERY',
    'CEDAR',
    'CONST.',
    'BUILDERS', 
    'PLUMBER',
    'CYCLES',
    'AFTERSCHOOL',
    'TUTOR',
    'CRAFTS',
    'CAMPING',
    '&',
    'CLASSIC',
    ' LOCAL', 
    'ORGANIZATION',
    'FLEET',
    'COMMUNAUTAIRE',
    ' WINDOW',
    'MEDICINE',
    'EXPRESSIONS',
    'ON TRACK', 
    'MARKET',
    ' GLASS',
    ' OU ', 
    'PIZZA'
]


prefix_extract_to_party_load_map = {
    'ADMIRAL' : '1',
    'ADM.' : '1',
    'ADM' : '1',
    'AIRMAN' : '2',
    'AMN' : '2',
    'BROTHER' : '3',
    'BRO.' : '3',
    'BRO' : '3',
    'CAPTAIN' : '4',
    'CAPT.' : '4',
    'CARDINAL' : '5',
    'COLONEL' : '6',
    'COL.' : '6',
    'COL' : '6',
    'COMMANDER' : '7',
    'COMM.' : '7',
    'COMM' : '7',
    'CORPORAL' : '8',
    'CPL.' : '8',
    'CPL' : '8',
    'DEAN' : '9',
    'DOCTOR' : '10',
    'DR.' : '10',
    'DR' : '10',
    'ESTATE OF' : '11',
    'FATHER' : '12',
    'GENERAL' : '13',
    'GEN.' : '13',
    'GEN' : '13',
    'GOVERNOR' : '14',
    'GOV.' : '14',
    'GOV' : '14',
    'HONORABLE' : '15',
    'HOURABLE' : '15',
    'HONOR' : '15',
    'HONOUR' : '15',
    'HON.' : '15',
    'HON' : '15',
    'JUDGE' : '16',
    'JUSTICE' : '17',
    'LT. GOVERNOR' : '18',
    'LT. GOV.' : '18',
    'LIEUTENANT' : '19',
    'LT.' : '19',
    'M.' : '20',
    'M' : '20',
    'MONSIEUR' : '20',
    'MONSIGNOR' : '20',
    'MGR' : '20',
    'MSGR' : '20',
    'MONS' : '20',
    'MS.' : '21',
    'MAJOR' : '22',
    'MAJ' : '22',
    'MISS' : '23',
    'MLLE' : '24',
    'MADEMOISELLE' : '24',
    'MME' : '25',
    'MADAME' : '25',
    'MADAM' : '25',
    'MR.' : '26',
    'MR' : '26',
    'MISTER' : '26',
    'MRS.' : '27',
    'MRS' : '27',
    'MAYOR' : '28',
    'PASTOR' : '29',
    'PTR.' : '29',
    'PR.' : '29',
    'CONSTABLE' : '30',
    'CST.' : '30',
    'PRESIDENT' : '31',
    'PRES.' : '31',
    'PRES' : '31',
    'PROFESSOR' : '32',
    'PROF.' : '32',
    'PROF' : '32',
    'RABBI' : '33',
    'REVEREND' : '34',
    'REV.' : '34',
    'REV' : '34',
    'REVD.' : '34',
    'REVD' : '34',
    'RIGHT HONORABLE' : '35',
    'RT HON.' : '35',
    'RT. HON.' : '35',
    'SENATOR' : '36',
    'SEN.' : '36',
    'SEN' : '36',
    'SERGEANT' : '37',
    'SGT.' : '37',
    'SGT' : '37',
    'SISTER' : '38',
    'SIS.' : '38',
    'SIS' : '38',
    'VICE-PRESIDENT' : '39',
    'VP' : '39',
    'V.P' : '39',
    'VP.' : '39',
    'V-P' : '39'
}

## AAC-:562, 616
extract_check_dict = {    
    'VIP' : ['Y'],
    'Credit Score Consent Indicator' : ['Y', 'N'],
    'Personal Info Consent' : ['0', '1', '2', '3', '4'],
    'Preferred Language' : ['E', 'F'],
    'Gender' : ['1', '2'],
    'Marital Status' : ['M', 'S'],
    'RecordType' : ['CHG', 'NEW', 'URGENT'],
    'Suffix' : ['Asst.V.P.', 'C.E.O.', 'C.F.O.', 'C.O.O.', 'C.P.A.', 'CharteredLifeUnd', 'CharteredP/CUnd', 'D.D.S.', 'D.O.', 'D.V.M.', 'Esquire', 'II', 'III', 'IV', 'Jr.', 'Jr', 'M.D.', 'Manager', 'Monsignor', 'NotoraryPublic', 'P.A.', 'P.C.', 'PhD', 'Pres.', 'Q.C.', 'R.N.', 'Seaman', 'Sec.', 'Sr.', 'Sr', 'Supervisor', 'Treasurer', 'V'],
    'Country' : ['CA', 'US'],
    'Product Line' : ['A','H'],
    'Relationship type' : ['AUNT','BOYFRIEND','BROTHER','BROTHER IN-LAW','COUSIN','DAUGHTER','DAUGHTER-IN-LAW','FATHER','FATHER-IN-LAW','FOSTER CHILD','GIRLFRIEND','GRANDDAUGHTER','GRANDFATHER','GRANDMOTHER','GRANDSON','HUSBAND','JOINT-OWNER','MOTHER','MOTHER-IN-LAW','Nanny','NEPHEW','NIECE','OTHER','PARENTS','PARTNER','ROOMMATE','SINGLE','SISTER','SISTER IN LAW','SON','SON-IN-LAW','UNCLE','WIFE'],
    'Prefix' : ['ADMIRAL', 'AIRMAN', 'BROTHER', 'CAPTAIN', 'CARDINAL', 'COLONEL', 'COMMANDER', 'CORPORAL', 'DEAN', 'DOCTOR', 'ESTATE OF', 'FATHER', 'GENERAL', 'GOVERNOR', 'HONORABLE', 'JUDGE', 'JUSTICE', 'LT. GOVERNOR', 'LIEUTENANT', 'M', 'MS.', 'MS', 'MAJOR', 'MISS', 'MLLE', 'MME', 'MR.', 'MR', 'MRS.', 'MRS', 'MAYOR', 'PASTOR', 'CONSTABLE', 'PRESIDENT', 'PROFESSOR', 'RABBI', 'REVEREND', 'RIGHT HONORABLE', 'SENATOR', 'SERGEANT', 'SISTER', 'VICE-PRESIDENT', '1', '2', '3', '4', '5', '6'],
    'Province/State Code' : ['AB','AK','AL','AR','AS','AZ','BC','CA','CO','CT','DC','DE','FL','GA','HI','IA','ID','IL','IN','KS','KY','LA','MA','MB','MD','ME','MI','MN','MO','MS','MT','NB','NC','ND','NE','NL','NH','NJ','NM','NS','NT','NU','NN','NV','NY','OH','OK','ON','OR','PA','PE','PR','QC','PQ','RI','SC','SD','SK','TN','TT','TX','UT','VA','VI','VT','WA','WI','WV','WY','YT'],
    'Policy Province' : ['AB','AK','AL','AR','AS','AZ','BC','CA','CO','CT','DC','DE','FL','GA','HI','IA','ID','IL','IN','KS','KY','LA','MA','MB','MD','ME','MI','MN','MO','MS','MT','NB','NC','ND','NE','NL','NH','NJ','NM','NS','NT','NU','NN','NV','NY','OH','OK','ON','OR','PA','PE','PR','QC','PQ','RI','SC','SD','SK','TN','TT','TX','UT','VA','VI','VT','WA','WI','WV','WY','YT'],
    'Occupation' : ['ASST.V.P.','C.E.O.','C.F.O.','C.O.O.','C.P.A.','CHARTEREDLIFEUND','CHARTEREDP/CUND','D.D.S.','D.O.','D.V.M.','ESQUIRE','II','III','IV','JR.','JR','M.D.','MANAGER','MONSIGNOR','NOTORARYPUBLIC','P.A.','P.C.','PHD','PRES.','Q.C.','R.N.','SEAMAN','SEC.','SR.','SR','SUPERVISOR','TREASURER','V','PRODUCTION','MANAGEMENT','ADMINISTRATIVE SUPPORT','ADMINISTRATIVE','PROTECTIVE SERVICE','FOOD & BEVERAGE','NURSE','PROFESSIONAL/TECHNICAL','HEALTH CARE SPECIALIST','HOSPITAL TECHNICIAN','MEDICAL TECHNICIAN','HEALTH SERVICE','SURVEYORS','ARCHITECT','BIOLOGIST','DOCTOR','VETERINARIANS','SCIENTIST','URBAN PLANNERS','AGRONOMIST','ACTUARY','ACCOUNTANT','ENGINEER','LAWYER, NOTARY','BELL (ADMIN & OFFICE STAFF)','NORTHERN (ADMIN & OFFICE STAFF)','CHARTERED ADMINISTRATION','INSURANCE BROKER & COMPANY','MUNICIPALITY EMPLOYEE - ADMINISTRATIVE','FEDERAL GOVT EMPLOYEE - ADMINISTRATIVE','GOVERNMENT MANAGEMENT','EDUCATOR','UNIVERSITY STAFF','COLLEGE EMPLOYEE - ADMINISTRATIVE','HOSPITAL ADMINISTRATIVE STAFF','UNIVERSITY EMPLOYEE - ADMINISTRATIVE','FINANCIAL SERVICES SPECIALIST','FIREFIGHTER','RETIRED','MARKETING & SALES','PERSONAL SERVICE','BUILDING & GROUND SERVICE','CONSTRUCTION TRADE','TRANSPORTATION & MATERIAL MOVING','MECHANIC, INSTALLER, REPAIRER','NOT EMPLOYED','NOT DISCLOSED','OTHER (PQ ONLY)']
}

## AAC-
extract_prefix_2_gender_mapping = {
'M' : '1',
'MS.' : '2',
'MS' : '2',
'MISS' : '2',
'MLLE' : '2',
'MME' : '2',
'MR.' : '1',
'MR' : '1',
'MRS.' : '2',
'MRS' : '2',
'SISTER' : '2',
'1' : '1',
'01' : '1',
'2' : '2',
'02' : '2',
'3' : '2',
'03' : '2',
'5' : '2',
'05' : '2'
}

## AAC-574
momo_rpa = [
'Asst.V.P.',
'C.E.O.', 
'C.F.O.', 
'C.O.O.', 
'C.P.A.', 
'CharteredLifeUnd', 
'CharteredP/CUnd', 
'D.D.S.', 
'D.O.', 
'D.V.M.', 
'Esquire', 
'II', 
'III', 
'IV', 
'Jr.', 
'Jr', 
'M.D.', 
'Manager', 
'Monsignor', 
'NotoraryPublic', 
'P.A.', 
'P.C.', 
'PhD', 
'Pres.', 
'Q.C.', 
'R.N.', 
'Seaman', 
'Sec.', 
'Sr.', 
'Sr', 
'Supervisor', 
'Treasurer', 
'V'
]

extractColNames=['source_system_client_no', 'grouping_id', 'loyalty_date', 'client_name', 'prefix', 'first_name', 'middle_name', 'last_name', 'suffix', 'deceased_indicator', 'client_mailing_address', 'care_of', 'address_line_1', 'address_line_2', 'city', 'province_state_code', 'postal_zip_code', 'country_code',  'phone_residential','consent_to_call', 'consent_ndncl_date', 'consent_line_of_business', 'consent_phone_number', 'consent_household_member_who_gave_consent', 'phone_business', 'phone_fax', 'phone_cell', 'phone_alternate', 'e_mail_address_primary', 'e_mail_address_alternate', 'declined_e_mail', 'preferred_contact_method', 'emergency_contact', 'best_time_to_contact', 'web_site_address', 'organization_type', 'industry_type', 'organization_established_date', 'birth_date', 'age', 'drivers_license_number', 'gender', 'occupation', 'marital_status', 'preferred_language', 'personal_info_consent', 'personal_info_consent_date', 'credit_score_consent_indicator', 'credit_score_consent_date', 'credit_score_consent_expiry_date', 'e_news_letters', 'special_e_news_letters_for_business_owners', 'e_campaigns', 'e_alerts_reminders', 'regular_mail', 'business_partners_affiliates', 'marketing_consent_last_updated_date', 'last_maintained_date', 'vip', 'vip_contact_rep', 'vip_reason', 'market_other_product', 'policy_documents', 'follow_up_date', 'grace_period_end_date', 'relationship_type', 'relationship_to', 'membership_since_date', 'membership_no', 'member_owner_name', 'member_of_member_owner_name', 'membership_association', 'membership_end_date', 'policy_number', 'product_line', 'x_date', 'customer_since_date', 'policy_role', 'policy_effective_date', 'policy_expiry_date', 'policy_province', 'region', 'group_name', 'group_number', 'office_no', 'office_name', 'converted_client_id', 'tax_exemption_id','recordtype']

extractFormalNames=['Source System Client No.','Grouping ID','Loyalty Date','Client Name','Prefix','First Name','Middle Name','Last Name','Suffix','Deceased Indicator','Client Mailing Address','Care Of','Address Line 1','Address Line 2','CITY','Province/State Code','Postal/ZIP Code','Country Code','Phone - Residential','Consent to Call','Consent-NDNCL Date','Consent-Line of Business','Consent-Phone Number','Consent-Household Member who gave consent','Phone - Business','Phone - Fax','Phone - Cell','Phone - Alternate','E-mail Address - Primary ','E-mail Address - Alternate','Declined E-mail','Preferred contact method','Emergency Contact','Best Time to Contact','Web Site Address','Organization Type','Industry Type','Organization Established Date','Birth Date','Age',"Driver's License Number",'Gender','Occupation','Marital Status','Preferred Language','Personal Info Consent','Personal Info Consent Date','Credit Score Consent Indicator','Credit Score Consent Date','Credit Score Consent Expiry Date','e-News Letters','Special e-News Letters for Business Owners','e-Campaigns','e-Alerts/ Reminders','Regular Mail','Business Partners/Affiliates','Marketing Consent Last Updated Date','Last Maintained Date','VIP','VIP Contact Rep','VIP Reason','Market Other Product','Policy Documents','Follow Up Date','Grace Period End Date','Relationship type','Relationship to','Membership Since Date','Membership #','Member Owner Name','Member Of Member Owner Name','Membership Association','Membership End Date','Policy Number','Product Line','X-Date','Customer Since Date','Policy Role','Policy Effective Date','Policy Expiry Date','Policy Province','Region','Group Name','Group Number','Office No','Office Name','Converted Client ID','Tax Exemption ID', 'RecordType']

extractColKey={}

for idx,key in enumerate(extractColNames):
    extractColKey[key] = idx


cifColNames = ['identifier','household_id','grouping_id','broker_acquisition_id','rollover_date','person_org_indicator','loyalty_date','organization_name','prefix','first_name','middle_name','last_name','suffix','deceased_indicator','alternate_first_name','alternate_last_name','preferred_first_name','preferred_last_name','care_of','address_line_1','address_line_2','city','province_state_code','postal_zip_code','country_code','phone_residential','phone_business','phone_fax','phone_cell','phone_alternate','e_mail_address_primary','e_mail_address_alternate','declined_e_mail','emergency_contact','best_time_to_contact','web_site_address','organization_type','industry_type','org_established_date','birth_date','gender','occupation','marital_status','language','personal_info_consent','credit_score_consent_indicator','credit_score_consent_date','e_news_letters','special_e_news_letters_for_business_owners','e_campaigns','e_alerts_reminders','regular_mail','business_partners_affiliates','coseco_admin_system_type','source_system_client_no','vip','vip_contact_rep','vip_reason','market_other_product','policy_documents','consent_last_update_date','follow_up_date']

cifFormalName=['Identifier','Household ID','Grouping Key','Broker Acquisition Id','Rollover Date','Person/Org Indicator','Loyalty Date','Organization Name','Prefix','First Name','Middle Name','Last Name','Suffix','Deceased Indicator','Alternate First Name','Alternate Last Name','Preferred First Name','Preferred Last Name','Attention','Address Line 1','Address Line 2','City','Province/State Code','Postal Code','Country Code','Phone - Residential','Phone - Business','Phone - Fax','Phone - Cell','Phone - Alternate','E-mail Address - Primary','E-mail Address - Alternate','Declined E-mail','Emergency Contact','Best Time to Contact','Web Site Address','Organizaton Type','Industry Type','Org Established Date','Birth Date','Gender','Occupation','Marital Status','Language','Personal Info Consent','Credit Score Consent Indicator','Credit Score Consent Last Updated Date','e-News Letters','Special e-News Letters for Business Owners','e-Campaigns','e-Alerts/Reminders','Regular Mail','Business Partners/Affiliates','COSECO Admin System Type','COSECO Admin Party ID','VIP Indicator','VIP Contact Rep','VIP Reason','Other Insurance Product Indicator','Policy Document Only Indicator','Consent Last Update Date','Preference Follow up Date']	
expectedColNum=len(cifColNames)

cifColKey = {}
for idx,key in enumerate(cifColNames):
    cifColKey[key] = idx

